[package]
name = "novanes"
version = "0.1.0"
authors = ["rincewound <aaargh@minddebugger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues="1.0.0"
minifb = "0.16"